export const GET_CATEGORIS = "GET_GATEGORIES"
export const GET_ONE_CATEGORIS = "GET_ONE_GATEGORIES"

export const CREATE_CATEGORIS = "CREATE_GATEGORIES"
export const DELETE_CATEGORIS = "DELETE_GATEGORIES"


